### ISSUE TITLE
FieldNameRenderer missing features and other expected behaviors

### ISSUE THREAD

**Issue by ralftokada** [SharePoint/sp-dev-fx-controls-react#116]
#### Category
[x] Enhancement

[x] Bug

[ ] Question

#### Version

 v1.7.0 

#### Expected / Desired Behavior / Question
I would like the FileNameRender control get the next behavior
     -DoubleClick is not customizabled -I would like to get the same behavior of a single click  achieved in the 1.7.0 version where the default behavior is suppressed
     -Share and Show Action menus are gone, desired behavior will be to leave them at it comes unless a customization is possible
     -Circle next to the Icon is selected when the link is clicked, default un-selected behavior is desired

    

#### Observed Behavior
Explained above

#### Steps to Reproduce
Install the 1.7.0 version and customize the render sub in the *.tsx file as follow

  @override
  public render(): React.ReactElement<{}> {
    return (
      <FieldNameRenderer
      text={"mylink"}
      isLink={true}
      filePath={null}
      isNew={false}
      hasPreview={false}
      onClick={() => this.button_click()}
      />
    );
  }

  public button_click(): any {
window.open("MyUrlHandlerProtocol:" + window.location.protocol + "//"
   + window.location.hostname + this.props.listItem.getValueByName("FileRef"),"_self");
    return "MyUrlHandlerProtocol:" + window.location.protocol + "//"
    + window.location.hostname + this.props.listItem.getValueByName("FileRef");
  }
}

#### Submission Guidelines
-      hasNew     option if it is not specified should detect if this is a new file and show the default new icon.
-      hasPreview  do not know what this does, please explain

Thanks!

**Comment by estruyf** [comment]
@AJIXuMuK can you take this one?

**Comment by AJIXuMuK** [comment]
Sorry, @estruyf. Lost the notification in email.

Hi @ralftokada.
Point by point :)
* DoubleClick - I will be working on it to add ability to override double-click behavior.
* Share and Show actions. It's really hard to do that. There is not problem to add the icons itself. But unfortunately, there is no way to initiate standard behavior. It means that it should be "duplicated". To my mind it's to complex and hard to maintain.
* Circle next to item. If you click directly to the text, the row is not selected. So, the behavior is the same as it is for OOTB control. If you want to prevent selecting row when you click anywhere in the cell you need to add `onclick` event handler to `event.domElement` in your Field Customizer and stop propagation there.
* `isNew`. The component itself is designed to information. It doesn't communicate to SharePoint directly to get properties. It should be done from the entity that is using the component. That's why there is `FieldRendererHelper` class that actually detects if the item is new:
```typescript
isNew: SPHelper.getRowItemValueByName(listItem, 'Created_x0020_Date.ifnew') === '1'
```
* `hasPreview`. I will need to update documentation on that one. Basically, this flag impacts on how the link is configured for the default behavior (if `onClick` is not provided): if `hasPreview` is set to false than the url will be equal to `filePath` property which will lead to direct download of the file; if `hasPreview` is set to true that the url will look like `#id=${filePath}&parent=${filePath.substring(0, filePath.lastIndexOf('/'))}` - it will notify core engine to show the preview when the link is clicked.

Let me know if the explanation makes sense of if you have any additional thoughts on that!
In a meanwhile I'll be working on double click and documentation for `hasPreview` flag.

**Comment by AJIXuMuK** [comment]
@estruyf please, assign it to me.

**Comment by ralftokada** [comment]
Hi @AJIXuMuK 
Great thanks, stopping the double click default behavior/propagation and execute it as the single customized click behavior will make a significant progress.
For me if hasPreview is set to true and notify the core engine to be displayed regardless of whether onClick is provided or not, this is the desired behavior.

Thanks again for keeping up with this development

**Comment by estruyf** [comment]
Closing the issue as version `1.8.0` has just been released.
