### ISSUE TITLE
spfx v 1.6

### ISSUE THREAD

**Issue by spdavid** [SharePoint/sp-dev-fx-controls-react#144]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

I am thinking about adding some functionality to the people picker to grab data from the graph. This requires SPFx 1.6 or greater. Also will have to add some webApiPermissionRequests or at least some documentation to set it up if people want to use that functionality.  Perhaps a setting UseGraph or PeopleSource property to define where the data is coming from.

Any reason why we cant upgrade the solution to SPFx1.6?

**Comment by AsishP** [comment]
@spdavid , all in favour for it. Few months ago started with an approach with @pnpjs/graph but didn't get time to finalize it. 
Few thoughts/queries to the above points.
1. Sorry, not aware of the impact with update to SPFx v1.6, so asking. hopefully the upgrade will not enforce users to upgrade their solutions to SPFx v1.6 in order to use graph client? Instead of that, could we create a package dependancy on ms-graphclient only? There is also @pnpjs/graph, will that work for simple cases?
2. Regarding Graph client use, if I am getting it right, it will mostly be used for Office 365 groups, to get users in them. If yes, may be we could add property Office365Groups (array property) and GraphClient (property for Graph client details). In this way, we could expand groups and add to current users. Thoughts?

**Comment by spdavid** [comment]
I was thinking about using some other endpoints like the https://graph.microsoft.com/v1.0/users with a filter to search for all users in the organization. and maybe some other endpoints to grab groups as well. In order to do this i need to add some permissions to the graph via the webApiPermissionRequests.  We will need v. 1.6 for this as that where the functionality for this went GA if I'm not mistaken. 1.5 it was under the experimental features. 

If we are not ready to upgrade to 1.6 then i can just copy the component out and use it in my project and apply my customization's. I can then do a pull request when we are ready for 1.6.  Not sure what the policy here is on the versioning. I personally have no problem keeping my projects in the latest version.

**Comment by AsishP** [comment]
Ok makes sense. However personally I think if we want to search all users in a tenancy, it would be a candidate for PeopleSearch control and not PeoplePicker control. Thoughts?  I am worried that by expanding it to all users through the control we might be losing user context and have to add entries to user information of a site if the users don't exist.

Regarding upgrade to v1.6, I will leave @estruyf to take a call on it. Yes in favour of keeping the package version up to date, won't know the impact on all controls. We already had an impact in Peoplepicker earlier when we upgrade Office fabric UI to latest but these impacts are fine and nothing we cannot handle :)

**Comment by joelfmrodrigues** [comment]
@spdavid  @AsishP  I have submitted a PR to upgrade to 1.6.0
