### ISSUE TITLE
Deleted items not put in recycle bin for ListItemAttachment

### ISSUE THREAD

**Issue by ThomasGranheim** [SharePoint/sp-dev-fx-controls-react#291]
#### Category
[ x] Enhancement

[ x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.13.0  ]

#### Expected / Desired Behavior / Question
Attachements should be sent to the recycle bin - since the control states it will!

#### Observed Behavior
Attached files are not sent to the site collection recycle bin after deleting it from the ListItemAttachement control.

#### Steps to Reproduce
Try to delete an item from the control - it will not appear in the recycle bin. 

#### Submission Guidelines
Add RecycleObject to the apiUrl the deleteAttachement method in SPService.ts and the attached file will be collected in the recycle bin:
`const apiUrl = `${webAbsoluteUrl}/_api/web/lists('${listId}')/items(${itemId})/AttachmentFiles/getByFileName('${encodeURIComponent(fileName)}')/RecycleObject`;`

Thanks!

**Comment by estruyf** [comment]
@ThomasGranheim thank you very much. Feel free to do a PR next time 😄, because you gave the solution in your issue, I have added you to the list of contributors for the `1.13.2` release.

Feel free to test out the latest beta with your change.

Here you can read more information on how you can test out the latest beta version: https://sharepoint.github.io/sp-dev-fx-controls-react/beta/

**Comment by estruyf** [comment]
This has just been released in the version `1.13.2`.
