### ISSUE TITLE
Wrong SPHelper reference in FieldLookupRenderer.tsx

### ISSUE THREAD

**Issue by rajajii** [SharePoint/sp-dev-fx-controls-react#320]
**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.15.0]

#### Observed Behavior
I am using FieldLookupRenderer in comination with office-ui-fabric-react DetailsList.
I setup columns dynamically based on view chosen by user in webpart properties. In IColumn onRender method i have following code: 

` itemProps.onRender =(el: any) => {
                  return <span>{el[item.StaticName] ? <FieldLookupRenderer lookups={el[item.StaticName]} fieldId={'8553196d-ec8d-4564-9861-3dbe931050c8'} context={this.props.ctx} />: ""}</span>
                };`
where el[item.StaticName] is :
![image](https://user-images.githubusercontent.com/20475581/58762241-8661a400-854e-11e9-909d-5fa90acf8b1a.png)

Now List view renders correctly but when i click on lookupfield link i get following error in debugger: 
![image](https://user-images.githubusercontent.com/20475581/58762299-fc660b00-854e-11e9-842c-370f89fbce0e.png)

From FieldLookupRenderer.tsx i can see code try to execute SPHelper.getLookupFieldListDispFormUrl
It looks like SPHelper reference is wrong in the file

**Comment by AJIXuMuK** [comment]
Hi @rajajii 
With such a configuration `FieldLookupRenderer` will not work.
All "Field" controls were developed to work inside SPFx Extensions, not web parts.

In case of `FieldLookupRenderer` if you provide `fieldId` it'll try to get current view id from the page and get needed information from there. And it will fail because you're not on List View page.

If you want to use it in DetailsList I would recommend to provide custom `onClick` handler or `dispFormUrl` property that contains a link to display form of the referenced list.

I have created an example of `FieldLookupRenderer` usage in web part. You can find it [here](https://github.com/AJIXuMuK/SPFx/tree/master/field-lookup-renderer-webpart).
Feel free to use it and ping me if there are any questions.

**Comment by rajajii** [comment]
Thank you @AJIXuMuK 
By providing dispFormUrl everything seems to work :)

**Comment by estruyf** [comment]
Closing this issue, as it seems to be solved.
