### ISSUE TITLE
Rich Text Editor Control Issue

### ISSUE THREAD

**Issue by subhasishmukhopadhyay** [SharePoint/sp-dev-fx-controls-react#345]
I have created a RichText control to use in List Form customization using custom spfx webpart. It is working fine to save rich text value while creating a new item but when trying to open existing list item then all other fields are loaded properly in the web part but rich text value is showing blank. I am trying to load the values from componetdidmount using the below code
sp.web.lists.getByTitle("list title").items.getById().get().then((item: Item) => {
this.setState({Title: item["Title"]});
this.setState({Date: new Date(parseInt(item["Date"].split("T")[0].split("-")[0]),parseInt(item["Date"].split("T")[0].split("-")[1])-1,parseInt(item["Date"].split("T")[0].split("-")[2]))});
this.setState({Month: {key:item["Month"]}});
this.setState({Year: {key:item["Year"]}});
this.setState({DocumentType: {key:item["Document_x0020_Type"]}});
this.setState({BA: {key:item["BA"]}});
this.setState({Division: {key:item["DIV"]}});
this.setState({ValueAmount: item["Value"]});
this.setState({Currency: {key:item["Currency"]}});
this.setState({DocID: item["Document_x0020_ID"]});
this.setState({Description: item["Description"]});
});

Here is the rich text control
<RichText value={this.state.Description} onChange={(text) => this.handleDescription(text)} />

#### Category
[ ] Enhancement

[Y ] Bug

[ ] Question

**Comment by jcrocke9** [comment]
Hi subhasishmukhopadhyay!

I've actually never answered a question in this forum before, but I too just ran into this and wanted to share!

My issue was that I was loading the control into state of the react component *before* I was getting the data.

So I have my control, like you, and I too was using PnPJs calls to get my data. 

The fix was to ensure that I loaded the control *after* getting the data.

I did it this way, but I'm sure there are many many other ways:
State:
`export interface IRichTextEditorState {
  value?: string;
  nowLoad?: boolean;
}`

Constructor:
`  constructor(props) {
    super(props);
    this.state = {
      value: "",
      nowLoad: false
    }
    this.onChange = this.onChange.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
  }`

Component snippet:
`            <div className={styles.column}>
              {this.state.nowLoad &&
                <RichText
                  value={this.state.value}
                  onChange={this.onChange}
                  isEditMode={true}
                />
              }
              <p>
                <a onClick={(e) => this.onSubmit(e)}><PrimaryButton text="Submit" /></a>
              </p>
            </div>`

And finally, the componentDidMount lifecycle method:
`  private componentDidMount(): void {
    sp.web.lists.getByTitle("AOP Projects2").items.getById(1).get()
      .then((item: IAopRichText) => {
        console.log(item.ProjectOverviewVal);
        this.setState({ value: item.ProjectOverviewVal });
      })
      .then(() => { this.setState({nowLoad: true})})
  }`

**_Thank you thank you thank you_** to the team who does this!

**Comment by martinmattiesv2** [comment]
@jcrocke9 Worked like charm !!! Thank you!

**Comment by subhasishmukhopadhyay** [comment]
thanks a lot. It worked.
